### ISSUE TITLE
Bebop - PCMD vs. Video Streaming

### ISSUE THREAD

**Issue by m3d** [ARDroneSDK3/libARCommands#4]
Is there any relation between streaming video (enabled via ARCOMMANDS_ID_ARDRONE3_MEDIASTREAMING_CMD_VIDEOENABLE) and sending move commands (ARCOMMANDS_ID_ARDRONE3_PILOTING_CMD_PCMD)? It looks like I am able to receive video packets without any problem until I send the very first PCMD (even it is False with zeros). After that I am no longer able to get any streamed video UDP packets. The only possibility is to reboot the drone. On the other hand the drone is accepting PCMD and flies up and down for example, but no video.

Is there some minimum frequency for sending PCMD? (I saw 20Hz in Jumping Sumo sample, but nothing for Bebop yet).
thanks a lot for any hint
   Martin

**Comment by N-Bz** [comment]
Hi,

When using the PCMDs, you should make sure that your send them with a fixed frequency (we use 40Hz / 25ms in FreeFlight), even if you're sending the same command every 25ms.

A change in the PCMD frequency is considered by the Bebop to be a "bad wifi" indicator. In this case, the bebop will decrease the video bandwidth (up to a "no video" condition if the indicator is really bad) in order to save the bandwidth for the piloting commands. When the PCMD frequency become stable again, the video bandwidth will rise again.

Regards,
Nicolas.

**Comment by m3d** [comment]
Hi Nicolas,
confirmed:
https://github.com/robotika/katarina/commit/a4f81c15abfd4cb4cf97b9c16837011794fbfcab
thank you :). If I keep sending PCMD at 40Hz now the video is still streaming. But in the second run it is not streaming until I start to send PCMD at 40Hz again. Should I send PCMD all the time or is there some command saying this is the end of "PCMD session"?
thanks a lot
   Martin

**Comment by N-Bz** [comment]
Hi,

No, there is no "end of PCMD session" command. Once you started sending PCMD to the bebop, you should continue until the end of your session.

Regards,
Nicolas.

**Comment by m3d** [comment]
OK, thank you
Martin
